### ISSUE TITLE
Добавление атрибутов в MX.MarshalManager

### ISSUE THREAD

**Issue by rareMaxim** [magicxor/MXUtils#1]
Есть ли в планах добавление атрибутов для маршалинга? Например:

```
TTest = class 
  public
    [ALIAS('Type')]
     Typ: String;
    [ALIAS('Unit')]
     Unt: Integer;
    [REVAL('', '*')]
     Filter: String;
    [DISABLE]
     BlaBlaBla: String;
  end;

  var X: Test;
  begin
    X := TTest.Create;
    X.Typ := 'XType';
    X.Unt := 2;
    X.Filter := '';
    X.BlaBlaBla := ':)';
    ShowMessage(X.AsJSON);
  end;

```

> {
>     "Type": "XType", 
>     "Unit": 2, 
>     "Filter": "*"
>  }

**Comment by magicxor** [comment]
Т.к. это очень тонкий враппер вокруг Data.DBXJSONReflect - не планируется добавление чего бы то ни было, выходящего за рамки стандартных возможностей.
Чтобы не сериализовать определённое поле, можно добавить к нему атрибут `[JSONMarshalled(false)]` и включить в uses `Data.DBXJSONReflect`.
Что-то более сложное, наверное, можно реализовать через атрибут [JSONReflect](http://docwiki.embarcadero.com/Libraries/XE8/en/Data.DBXJSONReflect.JSONReflect).

P.S.: Только что узнал о существовании нового юнита `REST.Json`. Если перейти на его использование (вместо `Data.DBXJSONReflect`), то да, можно будет воспользоваться атрибутами `JSONMarshalledAttribute` (чтобы не сериализовать поле) и `JSONNameAttribute` (для переименования). В приложении к Delphi Cookbook (2014) есть и пример более глубокого вмешательства в процесс сериализации - JSONInterceptorSample.

**Comment by rareMaxim** [comment]
Спасибо за ответ.
